library(phangorn)
library(ape)
genes = c("NP", "L", "GP", "VP24", "VP30", "VP35", "VP40")
trees = data.frame()
for(gene in genes){
  path=paste("~/bio_project/bio/output/",gene,".csv",sep="")
  matrix=read.csv(path,check.names=FALSE)
  tree=upgma(matrix)
}
matrix = read.csv("~/bio_project/bio/output/NP.csv")
tree_1 = upgma(matrix)
matrix = read.csv("~/bio_project/bio/output/L.csv")
tree_2 = upgma(matrix)
matrix = read.csv("~/bio_project/bio/output/GP.csv")
tree_3 = upgma(matrix)
matrix = read.csv("~/bio_project/bio/output/VP24.csv")
tree_4 = upgma(matrix)
matrix = read.csv("~/bio_project/bio/output/VP30.csv")
tree_5 = upgma(matrix)
matrix = read.csv("~/bio_project/bio/output/VP35.csv")
tree_6 = upgma(matrix)
matrix = read.csv("~/bio_project/bio/output/VP40.csv")
tree_7 = upgma(matrix)
consensus_tree = consensus(tree_1,tree_2,tree_3,tree_4,tree_5,tree_6,tree_7, p = 1, check.labels = TRUE)
path=paste("~/bio_project/bio/output/consenuns.png",sep="")
png(path)
plot(consensus_tree)
dev.off()